name: Flutter Project Setup

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.pat }}
jobs:
  setup_flutter_project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Install Git
        run: sudo apt-get -y install git

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create Flutter Project
        run: flutter create quiz_master --project-name quiz_master --org com.quizmaster

      - name: Set up Git repository
        run: |
          echo "Creating repository 3 Period"
          gh repo create quiz_master --public

      - name: Push to Repository
        run: |
          cd quiz_master
          git init
          git add .
          git commit -m "Automated commit"
          git remote add origin_with_token "https://${{ secrets.pat }}@github.com/rahulbhai9/quiz_master.git"
          git push origin_with_token
