name: Flutter Project Setup

on:
  push:
    branches:
      - main

jobs:
  setup_flutter_project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1

      - name: Install Git
        run: sudo apt-get -y install git

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create Flutter Project
        run: flutter create exam_traker

      - name: Set up Git repository
        run: |
          echo "Creating repository..."
          cd ${{ github.repository }}
          git init
          git add .
          git commit -m "first commit"
          git branch -M main
          git remote add origin https://github.com/rahulbhai9/fff.git
          git push -u origin main
